// <auto-generated />
namespace MarsRoverUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class userp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userp));
        
        string IMigrationMetadata.Id
        {
            get { return "201311291559273_userp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
