// <auto-generated />
namespace MarsRover.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initpos1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initpos1));
        
        string IMigrationMetadata.Id
        {
            get { return "201302251229318_initpos1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
