// <auto-generated />
namespace MarsRover.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class req : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(req));
        
        string IMigrationMetadata.Id
        {
            get { return "201302221238241_req"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
