// <auto-generated />
namespace MarsRover.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class comp3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(comp3));
        
        string IMigrationMetadata.Id
        {
            get { return "201302221532168_comp3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
