// <auto-generated />
namespace MarsRover.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fk));
        
        string IMigrationMetadata.Id
        {
            get { return "201302221459510_fk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
